name: Python app
# блок on. Здесь указываются события, при которых данный workflow должен запускаться.
on:
  pull_request:
    branches:
    - main
# Пришло время настроить сам процесс CI для кода. Для этого используется блок jobs.
# Он может включать в себя несколько шагов, которые показываются в отдельном интерфейсе после каждого события.
jobs:
  build:
    runs-on: ubuntu-latest  # у каждого шага указывается, где необходимо его запустить
                            # В данном случае используется runner внутри инфраструктуры github на базе ubuntu.

    strategy:
      matrix:
        python-version: [3.12, 3.11, 3.10]

    steps:  # в блоке steps описываются конкретные действия, которые выполняются в рамках конкретного шага:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ci_cd_requirements.txt ]; then pip install -r ci_cd_requirements.txt; fi

    - name: Run Flake8 and generate HTML report
      run: |
        mkdir -p flake8-report_${{ matrix.python-version }}
        flake8 .

    - name: Upload Flake8 HTML report
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: flake8-html-report-${{ matrix.python-version }}
        path: flake8-report-${{ matrix.python-version }}/

    - name: Notify Telegram on success
      if: success()
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
        -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
        -d text="✅ CI успешно завершeн на ветке ${{ github.ref_name }}!"